//created on: 2016-1-8
package myrules

import com.sankuai.meituan.sample.model.Employ;
//list any import classes here.
import com.sankuai.meituan.sample.model.Worker;


//declare any global variables here




rule "Total"
      ruleflow-group "sum_salary"
    when
        //conditions
        emp:Employ()
    then
        //actions
        System.out.println("exec rule Total!");
        double total=emp.getBasicSalary()+emp.getDutySalary()+emp.getBonusSalary();
        System.out.println("total:"+total);
        System.out.println("percent:"+emp.getPercent());
        System.out.println("total*percent:"+total*emp.getPercent());
        emp.setTotalSalary(total*emp.getPercent());
        
         System.out.println("total_salary:"+emp.getTotalSalary());

end
rule "listTest22222222"
       ruleflow-group "sum_salary"
       when
            emp:Employ(kk>0);
            
       then
       System.out.println("listTest22222222:"+emp.getKk());
end

rule "listTest3333333333333333"
       ruleflow-group "sum_salary"
       no-loop true
       when
            emp:Employ();
            
       then
       emp.setKk(emp.getKk());
       update(emp);
       System.out.println("listTest3333333333333333:"+emp.getKk());
end